### PR TITLE
Formatted (fixed)

### PR DESCRIPTION
**Pull request by theLAZYway01**
Fixed format, I put muting_with_force in messages
and put mute_with_force on the file

### CODE REVIEW

**Comment by theLAZYway01** [comment]
@Wild1145

**Comment by Wild1145** [comment]
All the following issues should be in one PR: #81 #82 #83 #84 Please do so and open a new request.

**Comment by theLAZYway01** [comment]
I do not know how to merge all 4 requests into one.. noob status

**Comment by Kent55** [comment]
@theLAZYway01 You will need to either use the command line (Git Bash) or through Netbeans (if you use that). Simply fork Darthcraft, create a separate branch and clone it to your computer. Make all the necessary edits, commit and push it, then you can create a pull request, which then @Wild1145 can merge into the master branch.

**Comment by theLAZYway01** [comment]
So downlod the source, make my changes, export it to a zip and upload that zip branch into a commit and push it?

**Comment by Kent55** [comment]
Fork this repo, then clone it to your computer. Once you've made all the changes push the changes and then create a pull request. You will either need to use the command line or if you use Netbeans you can do it through that. If you're on Windows: http://msysgit.github.io/ and Mac has Git installed by default.

**Pull request closed without merging**
